// ------- MEDICAL -----------
export const MEDICAL_ADD_START = 'MEDICAL_ADD_START';
export const MEDICAL_ADD_SUCCESS = 'MEDICAL_ADD_SUCCESS';
export const MEDICAL_ADD_FAIL = 'MEDICAL_ADD_FAIL';

export const MEDICAL_UPDATE_START = 'MEDICAL_UPDATE_START';
export const MEDICAL_UPDATE_SUCCESS = 'MEDICAL_UPDATE_SUCCESS';
export const MEDICAL_UPDATE_FAIL = 'MEDICAL_UPDATE_FAIL';

export const MEDICAL_FETCH_START = 'MEDICAL_FETCH_START ';
export const MEDICAL_FETCH_SUCCESS = 'MEDICAL_FETCH_SUCCESS';
export const MEDICAL_FETCH_FAIL = 'MEDICAL_FETCH_FAIL';

export const MEDICAL_DELETE_START = 'MEDICAL_DELETE_START ';
export const MEDICAL_DELETE_SUCCESS = 'MEDICAL_DELETE_SUCCESS';
export const MEDICAL_DELETE_FAIL = 'MEDICAL_DELETE_FAIL';

// ------- CONTACT -----------
export const CONTACT_ADD_START = 'CONTACT_ADD_START';
export const CONTACT_ADD_SUCCESS = 'CONTACT_ADD_SUCCESS';
export const CONTACT_ADD_FAIL = 'CONTACT_ADD_FAIL';

export const CONTACT_UPDATE_START = 'CONTACT_UPDATE_START';
export const CONTACT_UPDATE_SUCCESS = 'CONTACT_UPDATE_SUCCESS';
export const CONTACT_UPDATE_FAIL = 'CONTACT_UPDATE_FAIL';

export const CONTACT_FETCH_START = 'CONTACT_FETCH_START ';
export const CONTACT_FETCH_SUCCESS = 'CONTACT_FETCH_SUCCESS';
export const CONTACT_FETCH_FAIL = 'CONTACT_FETCH_FAIL';

export const CONTACT_DELETE_START = 'CONTACT_DELETE_START ';
export const CONTACT_DELETE_SUCCESS = 'CONTACT_DELETE_SUCCESS';
export const CONTACT_DELETE_FAIL = 'CONTACT_DELETE_FAIL';

// ------- PHOTO -----------
export const PHOTO_ADD_START = 'PHOTO_ADD_START';
export const PHOTO_ADD_SUCCESS = 'PHOTO_ADD_SUCCESS';
export const PHOTO_ADD_FAIL = 'PHOTO_ADD_FAIL';

export const PHOTO_UPDATE_START = 'PHOTO_UPDATE_START';
export const PHOTO_UPDATE_SUCCESS = 'PHOTO_UPDATE_SUCCESS';
export const PHOTO_UPDATE_FAIL = 'PHOTO_UPDATE_FAIL';

export const PHOTO_FETCH_START = 'PHOTO_FETCH_START ';
export const PHOTO_FETCH_SUCCESS = 'PHOTO_FETCH_SUCCESS';
export const PHOTO_FETCH_FAIL = 'PHOTO_FETCH_FAIL';

export const PHOTO_DELETE_START = 'PHOTO_DELETE_START ';
export const PHOTO_DELETE_SUCCESS = 'PHOTO_DELETE_SUCCESS';
export const PHOTO_DELETE_FAIL = 'PHOTO_DELETE_FAIL';

// ------- AUTH -----------
// signs out from all services - including firebase, facebook
export const CHECKING_LOGIN_STATE = 'CHECKING_LOGIN_STATE';
export const SIGN_OUT_ALL = 'SIGN_OUT_ALL';

export const INIT_USER_STATE = 'INIT_USER_STATE';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const LOGIN_GUEST_START = 'LOGIN_GUEST_START';
export const LOGIN_GUEST_SUCCESS = 'LOGIN_GUEST_SUCCESS';
export const LOGIN_GUEST_FAIL = 'LOGIN_GUEST_FAIL';

export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL';

export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

// mark if user is signed-in-to or signed-out-from firebase
export const SIGNED_IN_FIREBASE = 'SIGNED_IN_FIREBASE';
export const SIGNED_OUT_FIREBASE = 'SIGNED_OUT_FIREBASE';

// Facebook Auth actions
export const FACEBOOK_LOGIN_START = 'FACEBOOK_LOGIN_START';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const FACEBOOK_LOGIN_FAIL = 'FACEBOOK_LOGIN_FAIL';

// mark if user is signed-in-to or signed-out-from facebook
export const SIGNED_IN_FACEBOOK = 'SIGNED_IN_FACEBOOK';
export const SIGNED_OUT_FACEBOOK = 'SIGNED_OUT_FACEBOOK';

// ------------ Pet data -------------------------------
export const INIT_PET_STATE = 'INIT_PET_STATE';

export const PET_UPDATE_START = 'PET_UPDATE_START';
export const PET_UPDATE_SUCCESS = 'PET_UPDATE_SUCCESS';
export const PET_UPDATE_FAIL = 'PET_UPDATE_FAIL';

export const PET_FETCH_START = 'PET_FETCH_START';
export const PET_FETCH_SUCCESS = 'PET_FETCH_SUCCESS';
export const PET_FETCH_FAIL = 'PET_FETCH_FAIL';
